[green_agent]
agentbeats_id = "019bb6e1-15df-71d1-a84c-4408de001eae"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}"}

[[participants]]
agentbeats_id = "019bb6fa-67ad-7fe1-8b90-e96bf9e355e3"
name = "agent"
env = { NEBIUS_API_KEY = "${NEBIUS_API_KEY}"}

[config]
num_rounds = 1
